import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/globals/footer";
import NavMain from "@/components/global-header/nav-main";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`w-screen h-dvh flex flex-col justify-between ${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="max-w-[1440px] mx-auto">
          <NavMain />
          <main>{children}</main>
        </div>
        <Footer></Footer>
      </body>
    </html>
  );
}
