import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/globals/footer";
import NavMain from "@/components/global-header/nav-main";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body
        className={`min-h-screen flex flex-col justify-between ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="w-full ">
          <div className="w-full max-w-[1440px] mx-auto px-4">
            <NavMain />
          </div>
        </header>

        <main className="flex-1 w-full max-w-[1440px] mx-auto px-4">
          {children}
        </main>

        <footer className="w-full mt-8">
          <div className="w-full  mx-auto ">
            <Footer />
          </div>
        </footer>
      </body>
    </html>
  );
}
